### ISSUE TITLE
Saving Gracefully に存在しない部品についての記述がある

### ISSUE THREAD

**Issue by mikecat** [Tsukina-7mochi/turing-complete-unofficial#22]
Saving Gracefully のページに、以下の記述があります。

> このステージではSR Latch (Set-Reset Latch) という部品が追加されています

しかし、現在のバージョン 0.652 Beta では、該当の部品は存在しないようです。

**Comment by Tsukina-7mochi** [comment]
私の環境 (betaでないlatestバージョン) ではSR Latchが存在するのですが、スクリーンショットなどを送っていただくことは可能でしょうか？
betaで削除されるということであればlatestで削除された際に対応します。

![1444480_20220408225347_1](https://user-images.githubusercontent.com/60507815/162450087-e2e11d35-ba45-4326-8307-62fb2fbb6341.png)

**Comment by kobi32768** [comment]
同じく 0.652 Beta 環境 (Steam では非ベータ/通常バージョン、タイトル画面右下のバージョン情報による) にて SR Latch は表示されています
タイトル画面のメニューの options にて Allow Inline latches の項目にチェックが入っていると SR Latch のステージが出現するはずなのでそれが影響している可能性があります

**Comment by mikecat** [comment]
スクリーンショットです。

ゲームのバージョン: 0.652 Beta  
OS: Windows 10 Home x64

![20220408225927_1](https://user-images.githubusercontent.com/6667599/162451271-11968b8c-94bc-447a-bef7-5471d8e5a841.jpg)

**Comment by mikecat** [comment]
Allow inline latches をオンにして SR Latch をクリアすることで、Saving Gracefully でもSR Latch が出てくることが確認できました。

**Comment by Tsukina-7mochi** [comment]
おそらくAllow inline latchesを有効にしてSR LatchのステージをクリアしないとSR Latchコンポーネントを使用できないようですね...
情報ありがとうございます。そのように追記しようと思います。
